spring.application.name=air-quality
spring.datasource.url=jdbc:postgresql://localhost:5432/air_quality
spring.datasource.username=postgres
spring.datasource.password=31.10.01Nd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=air-quality-group
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

openweathermap.api.key=1d16d0705a71d96f18248d60c78d318a


